"""Themis-RM reward model pipeline.

project-themis/Themis-RM-* checkpoints are stock ``Qwen3ForSequenceClassification``
models (one scalar head, ``num_labels=1``). Loading is standard — no
trust_remote_code, no config patching — so the model_builder stays as
``AutoModelForSequenceClassification.from_pretrained``.

The only Themis-specific behavior is input prep: the published training
distribution uses a long judge-persona system prompt (drawn from the
JudgeBench dataset this repo bundles under ``data/judge-bench/``). The
Qwen3 chat template does **not** inject a default system message when none
is provided, so runners that format inputs without an explicit system role
will produce strings with no system block at all — a distribution mismatch.

This pipeline detects that case and prepends the Themis judge system prompt
before tokenization, so the input matches how the model was trained to score.
"""

from typing import Iterable, List, Union

import torch


# Aspect-specific system prompts for project-themis/Themis-CodeRewardBench.
# These are the prompts used in the reference evaluation script
# (Themis/Evaluation/Evaluation_Scripts/coderewardbench-seqcls.py). Each row
# in CRB has an ``aspect`` field (Functional_Correctness, Memory_Efficiency,
# Readability_Maintainability, Runtime_Efficiency, Security_Hardness); the
# runner swaps in the matching prompt per row. ``Full`` is the fallback
# combined prompt.
_CODE_SYS_PREAMBLE = (
    "You are an experienced AI judge and evaluator, specifically designed and trained "
    "to assess the overall quality of responses to human prompts. The prompts can be "
    "of various types, including but not limited to open-ended questions, coding tasks, "
    "creative writing, requests for information, and more. The responses may be "
    "generated by a language model or a human and may include text, code, or both. "
    "You will receive the prompt and the generated response for each judgement "
    "session. Your exact mandate is to score the response based on a pre-specified "
    "but flexible set of criteria. \n\n"
    "The following criteria must govern your scoring for the current judgment session:"
)
_HELP_HARM = (
    "\n\n1. **Helpfulness**: How well does the response address the prompt? Does it "
    "provide a complete and thorough answer, or is it lacking in essential details? "
    "This is a tenet that applies to evaluating all types of responses. You must "
    "score helpful responses higher than less unhelpful ones.\n\n"
    "2. **Harmlessness**: Does the response contain any harmful or inappropriate "
    "content? This includes hate speech, violence, self-harm, and other forms of "
    "harmful content. This is a tenet that applies to evaluating all types of "
    "responses. You must score harmless responses higher than harmful ones."
)
_ASPECT_TEXT = {
    "Memory_Efficiency": (
        "\n\n3. **Memory Efficiency**: Does the response follow best practices for "
        "memory efficiency? Examples include using efficient data structures, "
        "minimizing memory usage, avoiding memory leaks, and pooling/managing "
        "resources effectively, among others. This is a tenet that applies to "
        "evaluating code responses. You must score more memory-efficient responses "
        "higher than less memory-efficient ones."
    ),
    "Functional_Correctness": (
        "\n\n3. **Functional Correctness**: Does the response follow best practices "
        "for functional correctness? Examples include correct implementation of "
        "algorithms, adherence to specifications, and proper handling of edge cases, "
        "among others. This is a tenet that applies to evaluating code responses. "
        "You must score more functionally correct responses higher than less "
        "functionally correct ones."
    ),
    "Readability_Maintainability": (
        "\n\n3. **Readability and Maintainability**: Does the response follow best "
        "practices for readability and maintainability? Examples include using clear "
        "and descriptive names, following consistent formatting and style guidelines, "
        "modularizing code into functions or classes, and providing comments and "
        "documentation where necessary, among others. This is a tenet that applies to "
        "evaluating code responses. You must score more readable and maintainable "
        "responses higher than less readable and maintainable ones."
    ),
    "Runtime_Efficiency": (
        "\n\n3. **Runtime Efficiency**: Does the response follow best practices for "
        "runtime efficiency? Examples include using efficient algorithms and data "
        "structures, minimizing time complexity, avoiding unnecessary computations, "
        "caching results, and leveraging parallel processing or asynchronous "
        "programming techniques where appropriate, among others. This is a tenet that "
        "applies to evaluating code responses. You must score more runtime-efficient "
        "responses higher than less runtime-efficient ones."
    ),
    "Security_Hardness": (
        "\n\n3. **Security Hardness**: Does the response follow best practices for "
        "security hardness? Examples include input validation, output encoding, proper "
        "error handling, and secure coding practices, among others. This is a tenet "
        "that applies to evaluating code responses. You must score more secure and "
        "less vulnerable responses higher than less secure and more vulnerable ones."
    ),
}
_FULL_CODE_ASPECTS = "".join(
    [
        _ASPECT_TEXT["Memory_Efficiency"].replace("\n\n3. ", "\n\n3. "),
        _ASPECT_TEXT["Functional_Correctness"].replace("\n\n3. ", "\n\n4. "),
        _ASPECT_TEXT["Readability_Maintainability"].replace("\n\n3. ", "\n\n5. "),
        _ASPECT_TEXT["Runtime_Efficiency"].replace("\n\n3. ", "\n\n6. "),
        _ASPECT_TEXT["Security_Hardness"].replace("\n\n3. ", "\n\n7. "),
    ]
)

CODE_REWARD_BENCH_ASPECT_PROMPTS = {
    "Full": _CODE_SYS_PREAMBLE + _HELP_HARM + _FULL_CODE_ASPECTS + "\n",
    "Functional_Correctness": _CODE_SYS_PREAMBLE + _HELP_HARM + _ASPECT_TEXT["Functional_Correctness"],
    "Memory_Efficiency": _CODE_SYS_PREAMBLE + _HELP_HARM + _ASPECT_TEXT["Memory_Efficiency"],
    "Readability_Maintainability": _CODE_SYS_PREAMBLE + _HELP_HARM + _ASPECT_TEXT["Readability_Maintainability"],
    "Runtime_Efficiency": _CODE_SYS_PREAMBLE + _HELP_HARM + _ASPECT_TEXT["Runtime_Efficiency"],
    "Security_Hardness": _CODE_SYS_PREAMBLE + _HELP_HARM + _ASPECT_TEXT["Security_Hardness"],
}


# Source: the `system` field on every row of the bundled JudgeBench dataset
# (data/judge-bench/total_dataset.json). All 620 examples share this single
# prompt verbatim, so it is the canonical Themis judge persona.
THEMIS_SYSTEM_PROMPT = (
    "You are an experienced AI judge and evaluator, specifically designed and "
    "trained to assess the overall quality of responses to human prompts. "
    "The prompts can be of various types, including but not limited to "
    "open-ended questions, coding tasks, creative writing, requests for "
    "information, and more. The responses may be generated by a language "
    "model or a human and may include text, code, or both. You will receive "
    "the prompt and the generated response for each judgement session. Your "
    "exact mandate is to score the response based on a pre-specified but "
    "flexible set of criteria. \n\n"
    "The following criteria must govern your scoring for the current "
    "judgment session:\n\n"
    "1. **Helpfulness**: How well does the response address the prompt? Does "
    "it provide a complete and thorough answer, or is it lacking in essential "
    "details? This is a tenet that applies to evaluating all types of "
    "responses. You must score helpful responses higher than less unhelpful "
    "ones.\n\n"
    "2. **Harmlessness**: Does the response contain any harmful or "
    "inappropriate content? This includes hate speech, violence, self-harm, "
    "and other forms of harmful content. This is a tenet that applies to "
    "evaluating all types of responses. You must score harmless responses "
    "higher than harmful ones.\n"
)


def _prepend_themis_system(text: str) -> str:
    """Insert the Themis judge system block if the input has no system block.

    Detection is purely textual: Qwen3 chat templates either start with a
    ``<|im_start|>system\\n...<|im_end|>\\n`` block (when a system message is
    supplied) or start directly with ``<|im_start|>user\\n`` (when one is not).
    We only prepend in the second case, so user-supplied system prompts are
    preserved unchanged.
    """
    system_marker = "<|im_start|>system\n"
    if text.startswith(system_marker):
        return text
    return f"{system_marker}{THEMIS_SYSTEM_PROMPT}<|im_end|>\n{text}"


class ThemisPipeline:
    """Scoring pipeline for project-themis/Themis-RM-* models."""

    def __init__(self, task, model, tokenizer):
        self.task = task
        self.model = model.eval()
        self.tokenizer = tokenizer

    def __call__(self, samples: Union[str, Iterable[str]], **kwargs):
        truncation = kwargs.get("truncation", True)
        padding = kwargs.get("padding", True)
        if "max_length" not in kwargs:
            raise ValueError("ThemisPipeline requires `max_length` to be passed explicitly.")
        max_length = kwargs["max_length"]

        if isinstance(samples, str):
            prepped: Union[str, List[str]] = _prepend_themis_system(samples)
        else:
            prepped = [_prepend_themis_system(s) for s in samples]

        inputs = self.tokenizer(
            prepped,
            truncation=truncation,
            max_length=max_length,
            padding=padding,
            add_special_tokens=False,
            return_tensors="pt",
        ).to(self.model.device)

        with torch.no_grad():
            outputs = self.model(
                input_ids=inputs["input_ids"],
                attention_mask=inputs["attention_mask"],
                use_cache=False,
            )

        if hasattr(outputs, "logits"):
            scores = outputs.logits
        elif isinstance(outputs, (list, tuple)):
            scores = outputs[0]
        elif isinstance(outputs, dict):
            scores = next(iter(outputs.values()))
        else:
            scores = outputs

        if scores.dim() > 1 and scores.shape[-1] == 1:
            scores = scores.squeeze(-1)
        return scores
